name: Sistema de Calificaciones CI

on: [push, pull_request]

jobs:
  revision-notas:
    runs-on: ubuntu-latest

    steps:
    - name: Bajar Codigo
      uses: actions/checkout@v3

    - name: Preparar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar Librerias
      run: |
        pip install -r requirements.txt

    - name: Auditoria de Codigo (Pylint)
      run: |
        pylint notas.py --disable=C0114,C0116,C0103 --fail-under=8.0

    - name: Pruebas y Cobertura
      run: |
        coverage run -m unittest test_notas.py
        coverage report -m --fail-under=80